### ISSUE TITLE
Seeing "...  is not implemented" status messages

### ISSUE THREAD

**Issue by jrfnl** [crazy-max/ghaction-github-status#78]
### Behaviour

I've recently started seeing some ".... is not implemented" status messages, where - if I remember correctly - those statuses were previously reported via this action.

In particular I noticed the GitHub Pages status no longer reporting, while I use that to prevent potentially borking a GH Pages website if a deploy is run while there is an outage.

#### Steps to reproduce this issue

```yml
      - name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@v3
        with:
          pages_threshold: major_outage
```

#### Expected behaviour

Statuses being reported for all systems.

#### Actual behaviour

![image](https://user-images.githubusercontent.com/663378/210164572-8961a13f-e568-462f-bb6c-6cd5e1c92495.png)
